# Basic settings and Info
title: Kundan Vishnu Gaikwad
email: kundan@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Embedded Systems and IoT Enthusiast.<br>   
  Firmware Developer.  
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github:
  username:  kundan21099

linkedin_url: "https://www.linkedin.com/in/kundan-gaikwad/"  

# Collections settings
collections:
  research:
    output: true
    permalink: /research/:name/

# Build settings
theme: jekyll-theme-minimal 
plugins:
  - jekyll-feed
  - jekyll-github-metadata

# Markdown settings
markdown: kramdown
kramdown:
  auto_ids: true

# Exclude from processing.
#exclude:
#   - ./_layouts/
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
